#Ansible Playbook: snmp_acl.yaml
#Created by Chris Wood
#Updated: 9/14/2016

---

#switches is a subset of devices listed in the pre-defined inventory hosts files located in /etc/ansible/hosts.
#It will iterate through all hostames in the subset switches
- hosts: bedford
  gather_facts: no 
  connection: local
 
#Prompt user for SSH credentials
  vars_prompt: 
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password" 
    prompt: "Password"


  tasks:
  
#A provider contains all information needed to connect to a device. inventory_hostname is gathered from pre-defined inventory hosts file.
  - name: Define Provider
    set_fact:
      cli:
        host: "{{ inventory_hostname }}"
        username: "{{ mgmt_username }}"
        password: "{{ mgmt_password }}"

#Connects to switch and runs the given show command and moves all output to variable named "config".
  - name: Collect Running Config
    ios_command:
      provider: "{{ cli }}"
      commands:
        - show running-config
    register: config    

#copies contents of config variable to an ouput text file using the inventory_hostname as part of filename
  - name: Save Config to a File
    copy: 
      content: "{{ config.stdout_lines }}"
      dest: "/etc/ansible/switch_backups/config_{{ inventory_hostname }}.txt"

#Run show command to view existing snmp community name and output it to the screen. 
#Can add a verification step in here
  - name: Show Original SNMP Config
    ios_command: 
      provider: "{{ cli }}"
      commands:
        - show run | inc snmp
    register: orig_snmp

  - debug: var=orig_snmp.stdout_lines    


#Set new community string name with access list number
  - name: Change SNMP Community
    ios_config:
      provider: "{{ cli }}"
      lines:
         - snmp-server community test RW 99
      before: no snmp-server community public RO


#Create new ip access list and add permitted hosts
  - name: Create SNMP ACL
    ios_config:
      provider: "{{ cli }}"
      lines:
        - permit host test
      parents: ip access-list standard 99
      before: no ip access-list standard 99
     
#Run show command to view new snmp community information and output it to the screen.
  - name: Show New SNMP Config
    ios_command:
      provider: "{{ cli }}"
      commands:
        - show run | inc snmp
    register: new_snmp

  - debug: var=new_snmp.stdout_lines

 
#Write all changes to memory 
  - name: Write Memory
    ios_command: 
      provider: "{{ cli }}"
      commands: 
        - write memory
    register: write
  

  - debug: var=write.stdout_lines 




