---

- hosts: test
  gather_facts: no
  connection: local

  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"
   
  tasks: 
  
  - name: Define Provider
    set_fact:
     provider: 
       host: "{{ inventory_hostname }}"
       username: "{{ mgmt_username }}"
       password: "{{ mgmt_password }}"

  - name: Show Clock
    ios_command:
      provider: "{{ provider }}"
      commands: 
        - show clock
    register: clock

 
  - name: Backup Config 
    ntc_save_config:
      platform: cisco_ios
      host: "{{ inventory_hostname }}"
      username: "{{ mgmt_username }}"
      password: "{{ mgmt_passowrd }}"
      local_file: switch_backups\config_{{ inventory_hostname }}.cfg


  - debug: msg= "{{ clock.stdout }}"

